number_one = int(input("Number one"))
number_two = int(input("Number two"))
your_feelings = input("Your feelings after creating such a great code: ")
print("\n")
print("And let's create a calculator that can add 2 values")
print("Number one: ", number_one)
print("Number two: ", number_two)
sum1 = (number_one + number_two)
print("The sum of two numbers is equal: ", sum1)
print("\n")
print("Your feelings after creating such a great code: ", your_feelings)